---
title: '**Randomized Block Design (RBD)**'
output:
  pdf_document:
    latex_engine: pdflatex
  word_document: default
  html_document:
    df_print: paged
fontsize: 12pt
header-includes:
- \usepackage{times}
- \usepackage{geometry}
- \geometry{a4paper, landscape}
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(knitr)
library(kableExtra)

```

```{r, echo = FALSE, results='asis'}
cat("\\begin{center}\\section*{Analysis Report}\\end{center}")

 columns_to_export <- if (input$select_columns) {
          input$selected_columns
        } else {
          names(analysis_result)
        }

 for (col_name in columns_to_export) {
          col_result <- analysis_result[[col_name]]
   
  if (!is.null(col_result$ANOVA) && input$include_ANOVA) {
     cat("\\begin{center}\\textbf{ANOVA Table}\\end{center}")     
        table_to_export <- col_result$ANOVA
          
          kable(table_to_export,align = "c",row.names = FALSE,label = NULL) %>%
  kable_styling(bootstrap_options = c("striped", "hover"), full_width = FALSE) %>%
  row_spec(0, bold = TRUE) %>% column_spec(1, bold = TRUE)   
                 
  }
          
          
          
          
}
 
 
 
 if (input$include_CombinedFinalTable) {
       cat("\\begin{center}\\textbf{Combined Final Table}\\end{center}")
   
          table_to_export <- combine_final_tables(analysis_result)
          
          kable(table_to_export,align = "c",row.names = FALSE,label = NULL) %>%
  kable_styling(bootstrap_options = c("striped", "hover"), full_width = FALSE) %>%
  row_spec(0, bold = TRUE) %>% column_spec(1, bold = TRUE) }
  
          # final_table <- analysis_result[[input$data_col]]$final_table
          # if (!is.null(final_table)) {
          #   colnames(final_table)[2] <- paste(colnames(final_table)[2], " (", input$data_col, ")", sep = "")
          #   table_to_export <- final_table
          # } else {
          #   table_to_export <- data.frame(Message = "No final table available for the selected column.")
          # }
        

# cat("\\\\")

# cat("\\\\")


# Add the footer
cat("\\begin{flushright}\\small Report generated by: \\textbf{Agronomy, TNAU} \\end{flushright}")
```
